name:                candor
version:             0.1.0.0
github:              "ChrisPenner/candor"
license:             BSD3
author:              "Chris Penner"
maintainer:          "christopher.penner@gmail.com"
copyright:           "Chris Penner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Other

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ChrisPenner/candor#readme>

ghc-options: -Wall
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- megaparsec == 6.4.*
- text == 1.2.*
- mtl == 2.2.*
- lens == 4.15.*
- containers == 0.5.*
- rio == 0.0.*

library:
  source-dirs: src

executables:
  candor-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - candor
    - haskeline == 0.7.4.*
    - optparse-applicative == 0.14.0.*

tests:
  candor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - candor
    - hspec == 2.4.*
    - text == 1.2.*
