name:                candor
version:             0.1.0.0
github:              "ChrisPenner/candor"
license:             BSD3
author:              "Chris Penner"
maintainer:          "christopher.penner@gmail.com"
copyright:           "Chris Penner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Other

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ChrisPenner/candor#readme>

ghc-options: -Wall
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - LambdaCase
  - DerivingStrategies
  - DeriveFunctor
  - GADTs

dependencies:
- base >= 4.7 && < 5
- cereal
- megaparsec
- text
- mtl
- lens
- containers
- rio
- streams
- hashable

library:
  source-dirs: src

executables:
  candor-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - candor
    - haskeline
    - optparse-applicative

tests:
  candor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - candor
    - hspec
    - text
